---
functional:
  - Пользователь должен иметь возможность регистрации на сайте.
  - Пользователь должен иметь возможность авторизации на сайте.
  - Возможность выбора языка программирования в терминале баттла.
  - Мультиязычность задач (русский и английский).
  - Пользователь должен иметь возможность просмотра текущего тура  наблюдателем 
    в режиме online.
  - Уведомление о начале баттла. 
   
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован 
    для скорости работы.
  - Сайт должен быть удобным на мобильном устройстве.
  - Сайт должен быть протестирован на совместимость с последними версиями основных браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика
implicit:
  - Участник не может писать и изменять код соперника.
  - Зрители не могут писать код и вносить изменения в код участников.
  - Пользователи не могут вносить изменения в таблицу лидеров.
  - Участники не могут вносить изменения в предустановленную задачу баттла.
  - Участники батла не могут вводить и редактировать код в терминале соперника.
  - Отображение элементов сайта не должно искажаться в разных локациях (русский и английский).
